//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfPractice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetaDataContext : DbContext
    {
        public MetaDataContext()
            : base("name=MetaDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RBM_Columns> RBM_Columns { get; set; }
        public virtual DbSet<RBM_DBCatalogs> RBM_DBCatalogs { get; set; }
        public virtual DbSet<RBM_Tables> RBM_Tables { get; set; }
    }
}
