//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBM_Columns
    {
        public int ColumnID { get; set; }
        public Nullable<int> TableID { get; set; }
        public string ColumnName { get; set; }
        public string DataType { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public Nullable<int> Precision { get; set; }
        public Nullable<int> Scale { get; set; }
        public Nullable<byte> IsNullable { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<byte> IsPrimaryKey { get; set; }
        public string ColumnDesc { get; set; }
        public Nullable<byte> Flag { get; set; }
        public Nullable<System.DateTime> Date_Insert { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ColumnSeq { get; set; }
        public Nullable<int> NullifyData { get; set; }
    }
}
