//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBM_DBCatalogs
    {
        public int DBCatalogID { get; set; }
        public string DBCatalogName { get; set; }
        public string DBCatalogServer { get; set; }
        public Nullable<int> DBCatalogTypeID { get; set; }
        public Nullable<int> ProductVersionID { get; set; }
        public Nullable<System.DateTime> Date_Insert { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
