//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBM_Tables
    {
        public RBM_Tables()
        {
            this.RBM_Columns = new HashSet<RBM_Columns>();
        }
    
        public int TableID { get; set; }
        public string TableSchema { get; set; }
        public string TableName { get; set; }
        public string TableDesc { get; set; }
        public Nullable<decimal> RowIDPrefix { get; set; }
        public Nullable<byte> Flag { get; set; }
        public Nullable<System.DateTime> Date_Insert { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> DBCatalogID { get; set; }
    
        public virtual ICollection<RBM_Columns> RBM_Columns { get; set; }
        public virtual RBM_DBCatalogs RBM_DBCatalogs { get; set; }
    }
}
